/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class form1 extends javax.swing.JFrame {

    /**
     * Creates new form form1
     */
    public form1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_1 = new javax.swing.ButtonGroup();
        lbl_dados = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        lbl_mat = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_mat = new javax.swing.JTextField();
        lbl_curso = new javax.swing.JLabel();
        rdb_1a = new javax.swing.JRadioButton();
        rdb_2a = new javax.swing.JRadioButton();
        rdb_3a = new javax.swing.JRadioButton();
        rdb_1b = new javax.swing.JRadioButton();
        rdb_2b = new javax.swing.JRadioButton();
        rdb_3b = new javax.swing.JRadioButton();
        lbl_med = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_rest = new javax.swing.JTextArea();
        btn_apr = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbl_dados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_dados.setText("Dados Cadastrais");

        lbl_nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_nome.setText("Nome:");

        lbl_mat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_mat.setText("Matrícula:");

        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });

        lbl_curso.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbl_curso.setText("Informe os dados do seu curso:");

        rdb_1a.setText("Etim");
        rdb_1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_1aActionPerformed(evt);
            }
        });

        rdb_2a.setText("Mtec");

        rdb_3a.setText("Técnico");

        rdb_1b.setText("1° série");

        rdb_2b.setText("2° série");

        rdb_3b.setText("3° série");

        lbl_med.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbl_med.setText("Restrições médicas:");

        txt_rest.setColumns(20);
        txt_rest.setRows(5);
        jScrollPane1.setViewportView(txt_rest);

        btn_apr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_apr.setText("Apresentar Dados");
        btn_apr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aprActionPerformed(evt);
            }
        });

        btn_limpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        btn_sair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        lst_1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Matutino", "Vespertino", "Noturno" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lst_1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_mat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_mat)
                        .addGap(256, 256, 256))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdb_3b)
                                    .addComponent(rdb_2b)
                                    .addComponent(rdb_1b))
                                .addComponent(lbl_curso)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_med)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdb_1a)
                                    .addComponent(rdb_2a)
                                    .addComponent(rdb_3a))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_apr)
                                .addGap(79, 79, 79)
                                .addComponent(btn_limpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                                .addComponent(btn_sair)))
                        .addGap(73, 73, 73))))
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(lbl_dados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbl_dados)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_mat)
                    .addComponent(txt_mat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(lbl_curso)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdb_1a)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdb_2a))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdb_3a))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdb_1b)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdb_2b)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdb_3b)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_med)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_apr)
                    .addComponent(btn_limpar)
                    .addComponent(btn_sair))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        txt_nome.setText(" ");
        txt_mat.setText(" ");
        txt_rest.setText(" ");
        
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_aprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aprActionPerformed
        String curso = " ", serie = " ";
        
        String nome  = txt_nome.getText();
        String matr  = txt_mat.getText();
        String rest  = txt_rest.getText();
        
        String period = lst_1.getSelectedValue();
        
        if(rdb_1a.isSelected()){
            serie = rdb_1a.getText();
        }
        else{
            if(rdb_2a.isSelected()){
                serie = rdb_2a.getText();
            }
            else{
                serie = rdb_3a.getText();
            }
        }
        if(rdb_1b.isSelected()){
            curso = rdb_1b.getText();
        }
        else{
            if(rdb_2b.isSelected()){
                curso = rdb_2b.getText();
            }
            else{
                curso = rdb_3b.getText();
            }
        }
        
        form2 mostra = new form2(nome, matr, rest, period, curso, serie);
        
        mostra.setVisible(true);
        dispose();
            
    }//GEN-LAST:event_btn_aprActionPerformed

    private void rdb_1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_1aActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_apr;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_sair;
    private javax.swing.ButtonGroup grp_1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_curso;
    private javax.swing.JLabel lbl_dados;
    private javax.swing.JLabel lbl_mat;
    private javax.swing.JLabel lbl_med;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JList<String> lst_1;
    private javax.swing.JRadioButton rdb_1a;
    private javax.swing.JRadioButton rdb_1b;
    private javax.swing.JRadioButton rdb_2a;
    private javax.swing.JRadioButton rdb_2b;
    private javax.swing.JRadioButton rdb_3a;
    private javax.swing.JRadioButton rdb_3b;
    private javax.swing.JTextField txt_mat;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextArea txt_rest;
    // End of variables declaration//GEN-END:variables
}
