/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class form2 extends javax.swing.JFrame {
 
    public form2(String nome, String matr, String rest, String period, String curso, String serie) {
        initComponents();
        
        lbl_name.setText(nome);
        lbl_matricu.setText(matr);
        lbl_restri.setText(rest);
        lbl_period2.setText(period);
        lbl_curso2.setText(curso);
        lbl_serie2.setText(serie);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nome = new javax.swing.JLabel();
        lbl_mat = new javax.swing.JLabel();
        lbl_curso = new javax.swing.JLabel();
        lbl_serie = new javax.swing.JLabel();
        lbl_period = new javax.swing.JLabel();
        lbl_rest = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        lbl_name = new javax.swing.JLabel();
        lbl_matricu = new javax.swing.JLabel();
        lbl_curso2 = new javax.swing.JLabel();
        lbl_serie2 = new javax.swing.JLabel();
        lbl_period2 = new javax.swing.JLabel();
        lbl_restri = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbl_nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_nome.setText("Nome:");

        lbl_mat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_mat.setText("Matrícula:");

        lbl_curso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_curso.setText("Curso:");

        lbl_serie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_serie.setText("Série:");

        lbl_period.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_period.setText("Período:");

        lbl_rest.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_rest.setText("Restrições médicas:");

        btn_voltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        btn_sair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        lbl_name.setText(".");

        lbl_matricu.setText(".");

        lbl_curso2.setText(".");

        lbl_serie2.setText(".");

        lbl_period2.setText(".");

        lbl_restri.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_mat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_matricu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_name))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_period)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_period2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_rest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_restri))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbl_serie)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_curso2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_curso)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_serie2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                        .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(lbl_name))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_mat)
                    .addComponent(lbl_matricu))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_curso)
                    .addComponent(lbl_serie2))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_serie)
                    .addComponent(lbl_curso2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_period)
                    .addComponent(lbl_period2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_rest)
                    .addComponent(lbl_restri))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_voltar)
                    .addComponent(btn_sair))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        new form1().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new form2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel lbl_curso;
    private javax.swing.JLabel lbl_curso2;
    private javax.swing.JLabel lbl_mat;
    private javax.swing.JLabel lbl_matricu;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_period;
    private javax.swing.JLabel lbl_period2;
    private javax.swing.JLabel lbl_rest;
    private javax.swing.JLabel lbl_restri;
    private javax.swing.JLabel lbl_serie;
    private javax.swing.JLabel lbl_serie2;
    // End of variables declaration//GEN-END:variables
}
